DROP TABLE IF EXISTS USER;

DROP TABLE IF EXISTS post;

CREATE TABLE
  USER (id INTEGER PRIMARY KEY AUTOINCReMENT, username TEXT UNIQUE NOT NULL, password TEXT NOT NULL);

CREATE TABLE
  post (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    FOREIGN KEY (author_id) REFERENCES USER (id)
  );