DROP TABLE IF EXISTS user
;

DROP TABLE IF EXISTS post
;

CREATE TABLE
  user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )
;

CREATE TABLE
  post (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    FOREIGN KEY (author_id) REFERENCES user (id)
  )
;

CREATE TRIGGER trigger_post_updated AFTER
UPDATE ON post BEGIN
UPDATE post
SET
  updated = CURRENT_TIMESTAMP
WHERE
  rowid == NEW.rowid
;

END
;